import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

const arabicTranslations = {
  'La curiosité les fait grandir': 'الفضول يساعدهم على النمو',
  'Little Explorers crée des espaces où les enfants peuvent imaginer, tester, créer et découvrir à leur rythme.': 'توفر ليتل إكسبلوررز مساحة للأطفال ليتخيلوا ويجرّبوا ويبدعوا ويكتشفوا بإيقاعهم الخاص.',
  'Un univers créatif pour les petits explorateurs': 'عالم إبداعي للمستكشفين الصغار',
  'Imaginer · Essayer · S’émerveiller': 'نتخيّل · نجرّب · نندهش',
  'Little Explorers en quelques repères': 'ليتل إكسبلوررز في أرقام',
  'univers à explorer': 'عوالم للاستكشاف',
  'tranches d’âge': 'فئات عمرية',
  'curiosité encouragée': 'فضول نشجّعه',
  'NOTRE PETITE RECETTE': 'وصفتنا الصغيرة',
  'Grandir, à sa façon': 'ينمو بطريقته',
  'Chaque enfant avance à son rythme, avec la joie de découvrir en chemin.': 'يتقدم كل طفل بإيقاعه الخاص، مستمتعاً بالاكتشاف في كل خطوة.',
  'Créer sans limites': 'إبداع بلا حدود',
  'Des idées qui prennent forme avec les mains, les couleurs et beaucoup d’imagination.': 'أفكار تنبض بالحياة بالأيدي والألوان والكثير من الخيال.',
  'Explorer pour comprendre': 'نستكشف لنتعلّم',
  'On pose des questions, on teste, on observe… et on découvre ensemble.': 'نسأل ونجرب ونلاحظ... ثم نكتشف معاً.',
  'S’épanouir en confiance': 'ننمو بثقة',
  'Un cadre bienveillant où chaque petit progrès compte et où chacun trouve sa place.': 'بيئة داعمة نقدّر فيها كل تقدم صغير ويجد فيها الجميع مكانهم.',
  'DES PASSIONS À PARTAGER': 'شغف نتشاركه',
  'Des univers différents, une même envie : transmettre le plaisir d’apprendre.': 'عوالم مختلفة، ورغبة واحدة: مشاركة متعة التعلّم.',
  'Son univers': 'عالمها',
  'Fermer': 'إغلاق',
  'Aucune activité trouvée': 'لم يتم العثور على أنشطة',
  'Essayez de modifier vos filtres pour voir d’autres ateliers.': 'جرّبوا تغيير عوامل التصفية لرؤية ورشات أخرى.',
  'Modifier': 'تعديل',
  'Supprimer': 'حذف',
  'Choisir un enfant': 'اختيار طفل',
  'Sélectionner': 'اختيار',
  'Récapitulatif': 'ملخص التسجيل',
  'À sélectionner': 'يرجى الاختيار',
  'Tarif mensuel': 'السعر الشهري',
  'GRANDIR EN S’AMUSANT': 'نكبر بالمرح',
  'Accueil': 'الرئيسية',
  'Activités': 'الأنشطة',
  'Vacances': 'العطل',
  'À propos': 'من نحن',
  'Contact': 'اتصل بنا',
  'Inscrire mon enfant': 'سجّل طفلي',
  'Passer en arabe': 'التغيير إلى العربية',
  'Switch to French': 'التغيير إلى الفرنسية',
  'Bonjour,': 'مرحباً،',
  'Ouvrir le menu': 'فتح القائمة',
  'Fermer le menu': 'إغلاق القائمة',
  'Grandir en s’amusant': 'نكبر بالمرح',
  'Découvrir les ateliers': 'اكتشفوا الورشات',
  'Inscrire pour les ateliers': 'التسجيل في ورشات',
  'Catégories d’activités': 'فئات الأنشطة',
  'À découvrir': 'اكتشف',
  'Summer Adventure': 'مغامرة الصيف',
  'Robotique Junior — Lina': 'الروبوتات للصغار — لينا',
  'Petits scientifiques — Lina': 'علماء صغار — لينا',
  'LEUR CURIOSITÉ N’A PAS DE LIMITES': 'فضولهم لا حدود له',
  'Ici, les enfants apprennent en s’amusant.': 'هنا يتعلّم الأطفال وهم يستمتعون!',
  'Des ateliers créatifs, scientifiques et sportifs pour éveiller leur curiosité, révéler leurs talents et leur donner le goût de découvrir.': 'ورشات إبداعية وعلمية ورياضية لإيقاظ فضولهم واكتشاف مواهبهم وحبّ المعرفة.',
  'Découvrir nos activités': 'اكتشفوا أنشطتنا',
  'Voir les vacances': 'اكتشفوا العطل',
  'La petite tribu des curieux grandit !': 'عائلة المستكشفين الصغار تكبر!',
  'Des activités joyeuses.': 'أنشطة مليئة بالمرح.',
  'Des enfants épanouis.': 'وأطفال سعداء.',
  'De la création aux grandes découvertes, chaque atelier les aide à grandir en s’amusant.': 'من الإبداع إلى الاكتشافات الكبيرة، تساعدهم كل ورشة على النمو والاستمتاع.',
  'De la création aux grandes découvertes, chaque atelier les aide à grandir en s’amusant.': 'من الإبداع إلى الاكتشافات الكبيرة، تساعدهم كل ورشة على النمو والاستمتاع.',
  'Petits explorateurs': 'مستكشفون صغار',
  'Curieux créatifs': 'مبدعون فضوليون',
  'Jeunes inventeurs': 'مخترعون صغار',
  'Grands passionnés': 'شغوفون كبار',
  'ON FAIT QUOI AUJOURD’HUI ?': 'ماذا سنفعل اليوم؟',
  'Des activités pour': 'أنشطة تناسب',
  'toutes les envies': 'كل الاهتمامات',
  'Chaque enfant a son petit monde. À lui de choisir où l’aventure commence !': 'لكل طفل عالمه الخاص. يختار بنفسه أين تبدأ المغامرة!',
  'Chaque enfant a son petit monde. À lui de choisir où l’aventure commence !': 'لكل طفل عالمه الخاص. يختار بنفسه أين تبدأ المغامرة!',
  'Créer': 'الإبداع',
  'Construire': 'البناء',
  'Explorer': 'الاستكشاف',
  "S'exprimer": 'التعبير',
  'Programmer': 'البرمجة',
  'Bouger': 'الحركة',
  'Cuisiner': 'الطبخ',
  'Découvrir': 'الاكتشاف',
  'Peinture, dessin & imagination': 'الرسم والتلوين والخيال',
  'Robots, briques & inventions': 'الروبوتات والمكعبات والاختراعات',
  'Sciences, nature & découvertes': 'العلوم والطبيعة والاكتشافات',
  'Théâtre, musique & confiance': 'المسرح والموسيقى والثقة بالنفس',
  'Code, logique & jeux numériques': 'البرمجة والمنطق والألعاب الرقمية',
  'Sport, énergie & esprit d’équipe': 'الرياضة والطاقة وروح الفريق',
  'Recettes, goûts & petits chefs': 'وصفات ونكهات وطهاة صغار',
  'Nature, sorties & nouvelles aventures': 'الطبيعة والنزهات والمغامرات الجديدة',
  'Voir toutes les activités': 'عرض جميع الأنشطة',
  'découvrir les activités': 'اكتشفوا الأنشطة',
  'LES VACANCES, VERSION EXPLORATEURS !': 'عطلة بأسلوب المستكشفين!',
  'L’ÉTÉ S’ANNONCE GÉNIAL': 'صيف رائع بانتظاركم',
  'Des enfants en pleine aventure dans la nature': 'أطفال يعيشون مغامرة في الطبيعة',
  'Les vacances commencent': 'العطلة تبدأ',
  'ici !': 'من هنا!',
  'Deux semaines de découvertes, de copains et de souvenirs à raconter.': 'أسبوعان من الاكتشافات والأصدقاء والذكريات الجميلة.',
  'Petits groupes': 'مجموعات صغيرة',
  'En plein air & en atelier': 'في الهواء الطلق والورشات',
  'Une journée bien remplie': 'يوم مليء بالأنشطة',
  'Du 1 au 15 juillet': 'من 1 إلى 15 يوليو',
  '2 semaines': 'أسبوعان',
  '8 – 15 ans': '8 – 15 سنة',
  '09h – 16h': '09:00 – 16:00',
  'Inscriptions ouvertes': 'التسجيل مفتوح',
  'Deux semaines d’activités créatives, de sciences, de jeux et de découvertes en plein air.': 'أسبوعان من الأنشطة الإبداعية والعلوم والألعاب والاكتشافات في الهواء الطلق.',
  'Lundi': 'الاثنين',
  'Mardi': 'الثلاثاء',
  'Jeudi': 'الخميس',
  'Vendredi': 'الجمعة',
  'Creative Lab': 'مختبر الإبداع',
  'Robotique & inventions': 'الروبوتات والاختراعات',
  'Expériences scientifiques': 'تجارب علمية',
  'Cinéma & expression': 'السينما والتعبير',
  'Aventure en plein air': 'مغامرة في الهواء الطلق',
  '/ les 2 semaines': '/ لمدة أسبوعين',
  'Voir le programme': 'عرض البرنامج',
  'LE BONHEUR D’APPRENDRE': 'متعة التعلّم',
  'Pourquoi les parents': 'لماذا يختارنا',
  'nous choisissent ?': 'الأهل؟',
  'Parce qu’ici, apprendre ne ressemble jamais à une leçon. C’est une aventure à vivre, à son rythme.': 'لأن التعلّم هنا ليس درساً عادياً، بل مغامرة يعيشها الطفل على إيقاعه الخاص.',
  'En savoir plus sur nous': 'اكتشفوا المزيد عنا',
  'Encadrement bienveillant': 'رعاية واهتمام',
  'Des animateurs passionnés, toujours à l’écoute.': 'مشرفون شغوفون يصغون للأطفال دائماً.',
  'Pour que chaque enfant trouve sa place.': 'حتى يجد كل طفل مكانه المناسب.',
  'On apprend en faisant': 'نتعلّم بالتجربة',
  'Des activités concrètes et pleines de découvertes.': 'أنشطة عملية مليئة بالاكتشافات.',
  'Un cadre sécurisé': 'بيئة آمنة',
  'Leur bien-être et leur sécurité avant tout.': 'سلامتهم وراحتهم أولويتنا.',
  'Des idées qui grandissent': 'أفكار تنمو',
  'La créativité encouragée, sans jamais être jugée.': 'نشجّع الإبداع دون إصدار الأحكام.',
  'Chacun son rythme': 'لكل طفل إيقاعه',
  'Des ateliers imaginés pour chaque étape de l’enfance.': 'ورشات مناسبة لكل مرحلة من مراحل الطفولة.',
  'DES SOUVENIRS EN COULEURS': 'ذكريات بألوان زاهية',
  'Les petits moments': 'لحظات صغيرة',
  'deviennent grands': 'تصنع ذكريات كبيرة',
  'Un aperçu de leurs aventures chez Little Explorers.': 'لمحة عن مغامراتهم في ليتل إكسبلوررز.',
  'Les petits artistes': 'فنانون صغار',
  'L’atelier robotique': 'ورشة الروبوتات',
  'Expériences en folie': 'تجارب ممتعة',
  'Dehors, on explore': 'نستكشف في الخارج',
  'Les chefs en herbe': 'طهاة واعدون',
  'Place au spectacle': 'حان وقت العرض',
  'LES MOTS DES PARENTS': 'آراء الأهالي',
  'Portrait de': 'صورة',
  '« Depuis qu’elle a découvert les ateliers sciences, Lina nous pose mille questions par jour. Et surtout, elle a hâte d’y retourner ! »': '« منذ أن اكتشفت لينا ورشات العلوم، وهي تطرح علينا ألف سؤال كل يوم. والأجمل أنها متحمسة للعودة! »',
  'Atelier Petits scientifiques': 'ورشة العلماء الصغار',
  'Sarah, maman de Lina': 'سارة، أم لينا',
  '« Adam a pris confiance en lui et adore montrer les petits robots qu’il construit. Il compte les jours avant chaque atelier ! »': '« ازدادت ثقة آدم بنفسه وأصبح يحب عرض الروبوتات الصغيرة التي يصنعها. إنه يعد الأيام حتى موعد كل ورشة! »',
  'Karim, papa d’Adam': 'كريم، والد آدم',
  'Atelier Robotique Junior': 'ورشة الروبوتات للصغار',
  '« L’accueil est chaleureux, les activités sont variées et Maya rentre toujours avec une nouvelle histoire à raconter. »': '« الأجواء ودودة والأنشطة متنوعة، وتعود مايا دائماً بقصة جديدة ترويها لنا. »',
  'Nadia, maman de Maya': 'نادية، أم مايا',
  'Atelier créatif': 'ورشة إبداعية',
  '« On sent que chaque enfant est encouragé à son rythme. Yacine s’épanouit, apprend et surtout s’amuse beaucoup. »': '« نشعر بأن كل طفل يتلقى التشجيع حسب إيقاعه. ياسين ينمو ويتعلم والأهم أنه يستمتع كثيراً. »',
  'Amel, maman de Yacine': 'أمل، أم ياسين',
  'Code en s’amusant': 'البرمجة بمرح',
  'Navigation des témoignages': 'التنقل بين آراء الأهالي',
  'Témoignage précédent': 'الرأي السابق',
  'Témoignage suivant': 'الرأي التالي',
  'Afficher le témoignage': 'عرض الرأي',
  'À VOUS DE JOUER !': 'حان دوركم!',
  'Prêt à découvrir son': 'هل أنتم مستعدون لاكتشاف',
  'prochain': 'موهبته',
  'talent ?': 'القادمة؟',
  'Leur prochaine grande idée commence par un petit oui.': 'فكرتهم الكبيرة القادمة تبدأ بموافقتكم.',
  'LEUR CURIOSITÉ N’A PAS DE LIMITES': 'فضولهم لا حدود له',
  'ON FAIT QUOI AUJOURD’HUI ?': 'ماذا سنفعل اليوم؟',
  'GRANDIR À SON RYTHME': 'ينمو على إيقاعه',
  'Des programmes par âge': 'برامج تناسب كل عمر',
  'Des activités adaptées à chaque étape de la curiosité.': 'أنشطة مناسبة لكل مرحلة من مراحل الفضول.',
  'Des ateliers pensés pour éveiller toutes les curiosités.': 'ورشات لإيقاظ الفضول وحبّ الاستكشاف.',
  'APPRENDRE EN S’AMUSANT': 'نتعلّم ونستمتع',
  'À chaque enfant, son aventure': 'لكل طفل مغامرته',
  'Des ateliers pensés pour éveiller toutes les curiosités.': 'ورشات لإيقاظ الفضول وحبّ الاستكشاف.',
  'Catégorie': 'الفئة',
  'Toutes': 'الكل',
  'Âge': 'العمر',
  'Tous les âges': 'كل الأعمار',
  'Découvrir': 'اكتشف',
  'ans': 'سنوات',
  'Activité introuvable': 'النشاط غير موجود',
  'Voir toutes les activités': 'عرض جميع الأنشطة',
  'Un atelier pour apprendre en faisant, encadré par un animateur passionné. Adapté aux enfants de': 'ورشة للتعلّم بالتجربة بإشراف مشرف شغوف. مناسبة للأطفال من',
  'à': 'إلى',
  'Aucun prérequis': 'لا يشترط وجود خبرة',
  'Blouse fournie': 'المئزر متوفر',
  'Tout le matériel est fourni': 'جميع الأدوات متوفرة',
  'Tenue de sport': 'ملابس رياضية',
  'Tablier fourni': 'المريلة متوفرة',
  'Tenue confortable': 'ملابس مريحة',
  'Ouvert': 'متاح',
  ' / mois': ' / شهرياً',
  'Horaire': 'الموعد',
  'Lieu': 'المكان',
  'Places disponibles': 'الأماكن المتاحة',
  'Demander une inscription': 'طلب التسجيل',
  'DES VACANCES QUI BOUGENT': 'عطلة مليئة بالحركة',
  'Nos camps d’exploration': 'مخيمات الاستكشاف',
  'Des journées pleines de découvertes, de jeux et de nouvelles amitiés.': 'أيام مليئة بالاكتشافات والألعاب والصداقات الجديدة.',
  'Nos camps d’exploration': 'مخيمات الاستكشاف',
  'Des journées pleines de découvertes, de jeux et de nouvelles amitiés.': 'أيام مليئة بالاكتشافات والألعاب والصداقات الجديدة.',
  'Camp introuvable': 'المخيم غير موجود',
  'Voir les camps': 'عرض المخيمات',
  'Une semaine pleine d’idées': 'أسبوع مليء بالأفكار',
  'La galerie des explorateurs': 'معرض المستكشفين',
  'Un aperçu des activités et ateliers Little Explorers.': 'لمحة عن أنشطة وورشات ليتل إكسبلوررز.',
  'ON EST LÀ POUR VOUS': 'نحن هنا لمساعدتكم',
  'Parlons de vos explorateurs': 'أخبرونا عن مستكشفيكم',
  'Une question sur les ateliers ? Écrivez-nous, nous serons ravis de vous aider.': 'هل لديكم سؤال عن الورشات؟ راسلونا وسيسعدنا مساعدتكم.',
  'Merci pour votre message. Notre équipe vous répondra bientôt.': 'شكراً على رسالتكم. سيرد فريقنا عليكم قريباً.',
  'Votre message': 'رسالتكم',
  'Envoyer le message': 'إرسال الرسالة',
  'Parlons de vos explorateurs': 'أخبرونا عن مستكشفيكم',
  'Une question sur les ateliers ? Écrivez-nous, nous serons ravis de vous aider.': 'هل لديكم سؤال عن الورشات؟ راسلونا وسيسعدنا مساعدتكم.',
  'Merci pour votre message. Notre équipe vous répondra bientôt.': 'شكراً على رسالتكم. سيرد فريقنا عليكم قريباً.',
  'Votre nom': 'اسمكم',
  'Votre e-mail': 'بريدكم الإلكتروني',
  'Votre message': 'رسالتكم',
  'Envoyer le message': 'إرسال الرسالة',
  'APPRENDRE EN S’AMUSANT': 'نتعلّم ونستمتع',
  'La galerie des explorateurs': 'معرض المستكشفين',
  'Un aperçu des activités et ateliers Little Explorers.': 'لمحة عن أنشطة وورشات ليتل إكسبلوررز.',
  'La curiosité les fait grandir': 'الفضول يساعدهم على النمو',
  'Little Explorers crée des espaces où les enfants peuvent imaginer, tester, créer et découvrir à leur rythme.': 'توفر ليتل إكسبلوررز مساحة للأطفال ليتخيلوا ويجرّبوا ويبدعوا ويكتشفوا بإيقاعهم الخاص.',
  'Une équipe passionnée': 'فريق شغوف',
  'APPRENDRE EN S’AMUSANT': 'نتعلّم ونستمتع',
  'La curiosité les fait grandir': 'الفضول يساعدهم على النمو',
  'Little Explorers crée des espaces où les enfants peuvent imaginer, tester, créer et découvrir à leur rythme.': 'توفر ليتل إكسبلوررز مساحة للأطفال ليتخيلوا ويجرّبوا ويبدعوا ويكتشفوا بإيقاعهم الخاص.',
  'Une équipe passionnée': 'فريق شغوف',
  'Retour à l’accueil': 'العودة إلى الصفحة الرئيسية',
  'HEUREUX DE VOUS REVOIR': 'سعداء بعودتكم',
  'Connexion': 'تسجيل الدخول',
  'Accédez à votre espace parent.': 'ادخلوا إلى حساب ولي الأمر.',
  'E-mail': 'البريد الإلكتروني',
  'Mot de passe': 'كلمة المرور',
  'Se connecter': 'تسجيل الدخول',
  'Compte de démonstration introuvable. Essayez parent@example.com.': 'لم يتم العثور على الحساب التجريبي. جرّبوا parent@example.com.',
  'Pas encore de compte ?': 'ليس لديكم حساب؟',
  'Créer un compte': 'إنشاء حساب',
  'Démo : parent@example.com ou instructor@example.com': 'للتجربة: parent@example.com أو instructor@example.com',
  'BIENVENUE DANS L’AVENTURE': 'أهلاً بكم في المغامرة',
  'Confirmer le mot de passe': 'تأكيد كلمة المرور',
  'Créer mon compte': 'إنشاء حسابي',
  'Les mots de passe ne correspondent pas.': 'كلمتا المرور غير متطابقتين.',
  'Déjà inscrit·e ?': 'لديكم حساب بالفعل؟',
  'Prototype local : les données restent dans ce navigateur.': 'نسخة تجريبية محلية: تبقى البيانات في هذا المتصفح.',
  'Mon espace': 'حسابي',
  'Retour au site': 'العودة إلى الموقع',
  'Vue d’ensemble': 'نظرة عامة',
  'Mes enfants': 'أطفالي',
  'Inscriptions': 'التسجيلات',
  'Calendrier': 'التقويم',
  'Paiements': 'المدفوعات',
  'Profil': 'الملف الشخصي',
  'Enfants': 'الأطفال',
  'Activités': 'الأنشطة',
  'Inscriptions actives': 'التسجيلات النشطة',
  'Paiements en attente': 'مدفوعات معلّقة',
  'À venir': 'القادم',
  'Notifications': 'الإشعارات',
  'Votre prochaine séance approche': 'موعد جلستكم القادمة يقترب',
  'Aujourd’hui': 'اليوم',
  'Mon calendrier': 'تقويمي',
  'Prochaines séances': 'الجلسات القادمة',
  'Aucune séance à venir.': 'لا توجد جلسات قادمة.',
  'Statut': 'الحالة',
  'Date': 'التاريخ',
  'Montant': 'المبلغ',
  'En attente': 'قيد الانتظار',
  'Payé': 'مدفوع',
  'Les paiements sont des exemples de démonstration.': 'المدفوعات المعروضة أمثلة توضيحية.',
  'Mon profil': 'ملفي الشخصي',
  'Nom': 'الاسم',
  'Enregistrer': 'حفظ',
  'Profil enregistré sur cet appareil.': 'تم حفظ الملف الشخصي على هذا الجهاز.',
  'Gérez les profils et les activités de vos enfants.': 'أديروا ملفات وأنشطة أطفالكم.',
  'Ajoutez votre premier enfant': 'أضيفوا طفلكم الأول',
  'Créez un profil pour découvrir les activités adaptées.': 'أنشئوا ملفاً لاكتشاف الأنشطة المناسبة.',
  'Modifier le profil': 'تعديل الملف الشخصي',
  'Prénom': 'الاسم الأول',
  'Âge': 'العمر',
  'Annuler': 'إلغاء',
  'Enfant': 'الطفل',
  'Confirmée': 'مؤكد',
  'Les paiements sont des exemples de démonstration.': 'المدفوعات المعروضة أمثلة توضيحية.',
  'Profil enregistré sur cet appareil.': 'تم حفظ الملف الشخصي على هذا الجهاز.',
  'Navigation du tableau de bord': 'قائمة لوحة التحكم',
  'Activités': 'الأنشطة',
  'activités': 'أنشطة',
  'Samedi · 10:00': 'السبت · 10:00',
  'Mercredi · 14:00': 'الأربعاء · 14:00',
  'Samedi · 10:00': 'السبت · 10:00',
  'Robotique Junior, samedi à 10:00.': 'الروبوتات للصغار، السبت الساعة 10:00.',
  'samedi à 10:00.': 'السبت الساعة 10:00.',
  'Bonjour,': 'مرحباً،',
  'Gérez les profils et les activités de vos enfants.': 'أديروا ملفات وأنشطة أطفالكم.',
  'Ajouter un enfant': 'إضافة طفل',
  'Ajoutez votre premier enfant': 'أضيفوا طفلكم الأول',
  'Créez un profil pour découvrir les activités adaptées.': 'أنشئوا ملفاً لاكتشاف الأنشطة المناسبة.',
  'Modifier le profil': 'تعديل الملف الشخصي',
  'Annuler': 'إلغاء',
  'Enfant': 'الطفل',
  'Activité': 'النشاط',
  'Horaire': 'الموعد',
  'Confirmée': 'مؤكد',
  'Robotique Junior': 'الروبوتات للصغار',
  'Petits scientifiques': 'علماء صغار',
  'Atelier créatif': 'ورشة إبداعية',
  'Code en s’amusant': 'البرمجة بمرح',
  'Mini-athlètes': 'رياضيون صغار',
  'Les petits chefs': 'طهاة صغار',
  'Théâtre en scène': 'مسرح الأطفال',
  'Explorateurs nature': 'مستكشفو الطبيعة',
  'Samedi, 10:00 – 12:00': 'السبت، 10:00 – 12:00',
  'Mercredi, 14:00 – 15:30': 'الأربعاء، 14:00 – 15:30',
  'Dimanche, 10:00 – 11:00': 'الأحد، 10:00 – 11:00',
  'Samedi, 14:00 – 15:30': 'السبت، 14:00 – 15:30',
  'Dimanche, 15:00 – 16:00': 'الأحد، 15:00 – 16:00',
  'Mercredi, 10:00 – 11:30': 'الأربعاء، 10:00 – 11:30',
  'Samedi, 11:00 – 12:30': 'السبت، 11:00 – 12:30',
  'Mercredi, 09:00 – 11:00': 'الأربعاء، 09:00 – 11:00',
  '2 h / semaine': 'ساعتان / أسبوعياً',
  '1 h 30 / semaine': 'ساعة ونصف / أسبوعياً',
  '1 h / semaine': 'ساعة / أسبوعياً',
  'Alger': 'الجزائر',
  'Samedi': 'السبت',
  'Mercredi': 'الأربعاء',
  'Dimanche': 'الأحد',
  'octobre': 'أكتوبر',
  'septembre': 'سبتمبر',
  'Aucun résultat': 'لا توجد نتائج',
  'Explorer': 'استكشف',
  'Nos activités': 'أنشطتنا',
  'Vacances & camps': 'العطل والمخيمات',
  'Ateliers du moment': 'ورشاتنا الحالية',
  'Notre histoire': 'قصتنا',
  'Nos animateurs': 'مشرفونا',
  'Nous contacter': 'تواصلوا معنا',
  'Questions fréquentes': 'الأسئلة الشائعة',
  'On garde le contact ?': 'لنبقَ على تواصل؟',
  'Des nouvelles, des idées et nos prochains ateliers. Promis, que du chouette !': 'أخبار وأفكار وورشاتنا القادمة. نعدكم بكل ما هو ممتع!',
  'Votre adresse e-mail': 'بريدكم الإلكتروني',
  "S'inscrire à la newsletter": 'الاشتراك في النشرة البريدية',
  'En vous inscrivant, vous acceptez notre politique de confidentialité.': 'باشتراككم، توافقون على سياسة الخصوصية.',
  'Fait avec': 'صُنع بـ',
  'pour les petits curieux': 'للمستكشفين الصغار',
  'Des ateliers pour grandir,': 'ورشات للنمو،',
  's’émerveiller et s’amuser.': 'والدهشة والمرح.',
  'Confidentialité': 'الخصوصية',
  'Mentions légales': 'الإشعارات القانونية',
  'Conditions générales': 'الشروط والأحكام',
  'Grandir en s’amusant': 'نكبر بالمرح',
  'Robotique Junior — Lina': 'الروبوتات للصغار — لينا',
  'Petits scientifiques — Lina': 'علماء صغار — لينا',
  'samedi à 10:00.': 'السبت الساعة 10:00.',
  '1 octobre 2026': '1 أكتوبر 2026',
  '1 septembre 2026': '1 سبتمبر 2026',
  'Samedi · 10:00': 'السبت · 10:00',
  'Mercredi · 14:00': 'الأربعاء · 14:00',
  'Mercredi · 10:00': 'الأربعاء · 10:00',
  'Mercredi · 09:00': 'الأربعاء · 09:00',
  'Dimanche · 10:00': 'الأحد · 10:00',
  'Samedi · 14:00': 'السبت · 14:00',
  'Dimanche · 15:00': 'الأحد · 15:00',
  'Samedi · 11:00': 'السبت · 11:00',
  '4 – 6 ans': '4 – 6 سنوات',
  '7 – 9 ans': '7 – 9 سنوات',
  '10 – 13 ans': '10 – 13 سنة',
  '14 – 17 ans': '14 – 17 سنة',
  'toutes les envies': 'كل الاهتمامات',
  'De la création aux grandes découvertes, chaque atelier les aide à grandir en s’amusant.': 'من الإبداع إلى الاكتشافات الكبيرة، تساعدهم كل ورشة على النمو والاستمتاع.',
  'Chaque enfant a son petit monde. À lui de choisir où l’aventure commence !': 'لكل طفل عالمه الخاص. يختار بنفسه أين تبدأ المغامرة!',
  'Des ateliers pensés pour éveiller toutes les curiosités.': 'ورشات لإيقاظ الفضول وحبّ الاستكشاف.',
  'découvrir les activités': 'اكتشفوا الأنشطة',
  'Des enfants en pleine aventure dans la nature': 'أطفال يعيشون مغامرة في الطبيعة',
  'Du 1 au 15 juillet': 'من 1 إلى 15 يوليو',
  '2 semaines': 'أسبوعان',
  '8 – 15 ans': '8 – 15 سنة',
  '09h – 16h': '09:00 – 16:00',
  'Inscriptions ouvertes': 'التسجيل مفتوح',
  'Deux semaines d’activités créatives, de sciences, de jeux et de découvertes en plein air.': 'أسبوعان من الأنشطة الإبداعية والعلوم والألعاب والاكتشافات في الهواء الطلق.',
  'Lundi': 'الاثنين',
  'Mardi': 'الثلاثاء',
  'Jeudi': 'الخميس',
  'Vendredi': 'الجمعة',
  'Creative Lab': 'مختبر الإبداع',
  'Robotique & inventions': 'الروبوتات والاختراعات',
  'Expériences scientifiques': 'تجارب علمية',
  'Cinéma & expression': 'السينما والتعبير',
  'Aventure en plein air': 'مغامرة في الهواء الطلق',
  'Les petits artistes': 'فنانون صغار',
  'L’atelier robotique': 'ورشة الروبوتات',
  'Expériences en folie': 'تجارب ممتعة',
  'Dehors, on explore': 'نستكشف في الخارج',
  'Les chefs en herbe': 'طهاة واعدون',
  'Place au spectacle': 'حان وقت العرض',
  '« Depuis qu’elle a découvert les ateliers sciences, Lina nous pose mille questions par jour. Et surtout, elle a hâte d’y retourner ! »': '« منذ أن اكتشفت لينا ورشات العلوم، وهي تطرح علينا ألف سؤال كل يوم. والأجمل أنها متحمسة للعودة! »',
  'Atelier Petits scientifiques': 'ورشة العلماء الصغار',
  'Nos camps d’exploration': 'مخيمات الاستكشاف',
  'Des journées pleines de découvertes, de jeux et de nouvelles amitiés.': 'أيام مليئة بالاكتشافات والألعاب والصداقات الجديدة.',
  'La galerie des explorateurs': 'معرض المستكشفين',
  'Un aperçu des activités et ateliers Little Explorers.': 'لمحة عن أنشطة وورشات ليتل إكسبلوررز.',
  'ON EST LÀ POUR VOUS': 'نحن هنا لمساعدتكم',
  'Parlons de vos explorateurs': 'أخبرونا عن مستكشفيكم',
  'Une question sur les ateliers ? Écrivez-nous, nous serons ravis de vous aider.': 'هل لديكم سؤال عن الورشات؟ راسلونا وسيسعدنا مساعدتكم.',
  'Merci pour votre message. Notre équipe vous répondra bientôt.': 'شكراً على رسالتكم. سيرد فريقنا عليكم قريباً.',
  'Envoyer le message': 'إرسال الرسالة',
  'Little Explorers crée des espaces où les enfants peuvent imaginer, tester, créer et découvrir à leur rythme.': 'توفر ليتل إكسبلوررز مساحة للأطفال ليتخيلوا ويجرّبوا ويبدعوا ويكتشفوا بإيقاعهم الخاص.',
  'Robotique & technologie': 'الروبوتات والتكنولوجيا',
  'Sciences & nature': 'العلوم والطبيعة',
  'Arts plastiques': 'الفنون التشكيلية',
  'CAP SUR L’AVENTURE': 'انطلقوا نحو المغامرة',
  'UN PEU DE NOUS DANS VOTRE BOÎTE MAIL': 'رسائلنا تصلكم إلى بريدكم',
  'ON SE RENCONTRE ?': 'هل نلتقي؟',
  'Le programme des vacances': 'برنامج العطلة',
  'Les bonnes nouvelles': 'أخبار جميلة',
  'Et si on explorait ensemble ?': 'ما رأيكم أن نستكشف معاً؟',
  'Laissez-nous vos coordonnées et nous vous envoyons tous les détails du Summer Adventure !': 'اتركوا بياناتكم وسنرسل إليكم كل تفاصيل مغامرة الصيف!',
  'Inscrivez-vous à notre newsletter pour recevoir nos prochains ateliers.': 'اشتركوا في نشرتنا لتصلكم أخبار ورشاتنا القادمة.',
  'Dites-nous comment vous joindre, notre équipe vous aidera à trouver l’atelier parfait.': 'أخبرونا كيف نتواصل معكم، وسيساعدكم فريقنا في اختيار الورشة المناسبة.',
  'Ex. Sarah Benali': 'مثال: سارة بن علي',
  'bonjour@exemple.com': 'bonjour@exemple.com',
  'Âge de votre enfant': 'عمر طفلكم',
  'Choisir une tranche d’âge': 'اختاروا الفئة العمرية',
  'Je m’inscris': 'أشترك',
  'Être recontacté(e)': 'أرغب في التواصل معي',
  'Sans engagement · Vos informations restent confidentielles': 'دون التزام · معلوماتكم سرية',
  'Merci, c’est noté !': 'شكراً، تم تسجيل طلبكم!',
  'Notre équipe revient vers vous très vite pour préparer la prochaine aventure.': 'سيتواصل معكم فريقنا قريباً للتحضير للمغامرة القادمة.',
  'À très bientôt !': 'إلى اللقاء قريباً!',
  'Compte de démonstration introuvable. Essayez parent@example.com.': 'لم يتم العثور على الحساب التجريبي. جرّبوا parent@example.com.',
  'Démo : parent@example.com ou instructor@example.com': 'للتجربة: parent@example.com أو instructor@example.com',
  'Prototype local : les données restent dans ce navigateur.': 'نسخة تجريبية محلية: تبقى البيانات في هذا المتصفح.',
  'Les mots de passe ne correspondent pas.': 'كلمتا المرور غير متطابقتين.',
  'Robotique Junior, samedi à 10:00.': 'الروبوتات للصغار، السبت الساعة 10:00.',
  'Profil enregistré sur cet appareil.': 'تم حفظ الملف الشخصي على هذا الجهاز.',
  'Activités': 'الأنشطة',
  'activités': 'أنشطة',
  'Gérez les profils et les activités de vos enfants.': 'أديروا ملفات وأنشطة أطفالكم.',
  'Ajouter un enfant': 'إضافة طفل',
  'Ajoutez votre premier enfant': 'أضيفوا طفلكم الأول',
  'Créez un profil pour découvrir les activités adaptées.': 'أنشئوا ملفاً لاكتشاف الأنشطة المناسبة.',
  'Modifier le profil': 'تعديل الملف الشخصي',
  'Prénom': 'الاسم الأول',
  'Confirmer le mot de passe': 'تأكيد كلمة المرور',
  'Le programme des vacances': 'برنامج العطلة',
  'Summer Adventure': 'مغامرة الصيف',
  'À découvrir': 'اكتشف',
  'Bonjour,': 'مرحباً،',
  'Navigateurs': 'قائمة لوحة التحكم',
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('little-explorers-language') || 'fr');
  const arabic = language === 'ar';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = arabic ? 'rtl' : 'ltr';
    document.documentElement.classList.toggle('rtl', arabic);
    document.body.classList.toggle('rtl', arabic);
    document.title = arabic
      ? 'ليتل إكسبلوررز — فضولهم لا حدود له'
      : 'Little Explorers — La curiosité en grand';
  }, [language, arabic]);

  const value = useMemo(() => ({
    arabic,
    language,
    toggleLanguage: () => setLanguage((current) => {
      const next = current === 'ar' ? 'fr' : 'ar';
      localStorage.setItem('little-explorers-language', next);
      return next;
    }),
    t: (text) => arabic ? (arabicTranslations[text] || text) : text,
  }), [arabic, language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
